qodana:
  only:
    - dev
    - master
    - muhmad
    - merge_requests
  image:
    name: jetbrains/qodana-php
    entrypoint: [ "" ]
  variables:
    QODANA_TOKEN: $qodana_token
  script:
    - qodana --save-report --results-dir=$CI_PROJECT_DIR/.qodana
