version: '3'

services:
    app:
        build: .
        volumes:
            - .:/var/www
        ports:
            - "81:80"
        depends_on:
            - db

    db:
        image: mysql:8.0
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}

volumes:
    db-data:
