version: '3'

services:
    app:
        image: php:8.2-apache
        volumes:
            - ./src:/var/www/html
        ports:
            - "81:80"

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: portal$0909Mportal$0909M
            MYSQL_DATABASE: portal_backend
            MYSQL_USER: portal_admin
            MYSQL_PASSWORD: portal$0909M

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: portal$0909Mportal$0909M
