version: '3'

networks:
    webapp:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: ${APP_NAME}_nginx
        ports:
            - "8002:80"
        links:
            - php
        volumes:
            - ./satreps:/var/www/html
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
            - ./docker/logs/nginx:/var/log/nginx:rw  # Corrected volume path
        depends_on:
            - php
            - mysql  # Replace 'postgres' with 'mysql'
        networks:
            - webapp

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ${APP_NAME}_php
        volumes:
            - ./satreps:/var/www/html
        ports:
            - "9002:9000"
        networks:
            - webapp

    mysql: # Change 'postgres' to 'mysql'
        image: mysql:8.0
        container_name: ${APP_NAME}_mysql
        restart: unless-stopped
        ports:
            - "3312:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql  # Corrected volume path
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - webapp

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${APP_NAME}_phpmyadmin
        restart: unless-stopped
        ports:
            - "8082:80"
        environment:
            PMA_HOST: mysql  # Change to 'mysql' to match the service name
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
        depends_on:
            - mysql  # Make sure phpMyAdmin starts after MySQL
        networks:
            - webapp
